#!/usr/bin/env python3
"""Generate the Unicode script table that bin/auto-lang.lua reads."""

from __future__ import annotations

import os
import urllib.request
from pathlib import Path


ROOT = Path(os.environ.get("PIXI_PROJECT_ROOT", Path(__file__).resolve().parents[1]))
DESTINATION = ROOT / "bin" / "script-ranges.lua"

# Pinned: a released version of the Unicode Character Database is immutable, so
# the generated table changes only when this line does. The checked-in output is
# what the build reads; nothing downloads anything at render time.
VERSION = "15.0.0"
UCD = f"https://www.unicode.org/Public/{VERSION}/ucd/"
# The cache is per release, so raising VERSION fetches that release rather than
# relabelling the files an earlier one left behind under the same names.
CACHE = ROOT / ".cache" / "unicode" / VERSION
FILES = [
    "Scripts.txt",
    "ScriptExtensions.txt",
    "PropertyValueAliases.txt",
    "extracted/DerivedBidiClass.txt",
]

# The scripts a document may map to a language. Adding one here and re-running
# this script is all it takes; the filter itself knows nothing about scripts.
# Latin earns its place without ever being mapped: the filter has to recognise
# it as a script to end a run, rather than absorbing it as neutral text.
SCRIPTS = [
    "Arabic", "Armenian", "Bengali", "Bopomofo", "Cyrillic", "Devanagari",
    "Ethiopic", "Georgian", "Greek", "Gujarati", "Gurmukhi", "Han", "Hangul",
    "Hebrew", "Hiragana", "Kannada", "Katakana", "Khmer", "Lao", "Latin",
    "Malayalam", "Myanmar", "Sinhala", "Syriac", "Tamil", "Telugu", "Thaana",
    "Thai", "Tibetan",
]


def fetch(name: str) -> str:
    path = CACHE / name.rsplit("/", 1)[-1]
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        request = urllib.request.Request(
            UCD + name, headers={"User-Agent": "font-pattern/0.1"}
        )
        with urllib.request.urlopen(request, timeout=120) as response:
            path.write_bytes(response.read())
    return path.read_text(encoding="utf-8")


def records(text: str):
    """Yield (first, last, value) for each data line of a UCD file."""
    for line in text.splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        field, _, value = line.partition(";")
        first, _, last = field.strip().partition("..")
        low = int(first, 16)
        yield low, int(last, 16) if last else low, value.strip()


def merge(ranges: list[tuple[int, int]]) -> list[list[int]]:
    """Sort and coalesce ranges so the filter can binary-search them."""
    merged: list[list[int]] = []
    for low, high in sorted(ranges):
        if merged and low <= merged[-1][1] + 1:
            merged[-1][1] = max(merged[-1][1], high)
        else:
            merged.append([low, high])
    return merged


def render(name: str, ranges: list[list[int]]) -> str:
    body = ", ".join(f"{{0x{low:04X},0x{high:04X}}}" for low, high in ranges)
    return f"    {name} = {{{body}}},"


def main() -> None:
    aliases = {}
    for line in fetch("PropertyValueAliases.txt").splitlines():
        fields = [field.strip() for field in line.split("#")[0].split(";")]
        if len(fields) >= 3 and fields[0] == "sc":
            aliases[fields[1]] = fields[2]

    wanted = set(SCRIPTS)

    # Script: the code point's own script.
    strong: dict[str, list[tuple[int, int]]] = {name: [] for name in SCRIPTS}
    for low, high, value in records(fetch("Scripts.txt")):
        if value in wanted:
            strong[value].append((low, high))

    # Script_Extensions: Common and Inherited code points that nevertheless
    # belong with particular scripts, such as 。 and 」 with Han. UAX #24 is
    # what makes these follow their neighbours instead of the surrounding text.
    extensions: dict[str, list[tuple[int, int]]] = {name: [] for name in SCRIPTS}
    for low, high, value in records(fetch("ScriptExtensions.txt")):
        for code in value.split():
            name = aliases.get(code, code)
            if name in wanted:
                extensions[name].append((low, high))

    # A script is right-to-left when its own code points are bidi class R or AL.
    rtl_points: set[int] = set()
    for low, high, value in records(fetch("extracted/DerivedBidiClass.txt")):
        if value in {"R", "AL"}:
            rtl_points.update(range(low, high + 1))
    rtl = [
        name
        for name in SCRIPTS
        if any(
            point in rtl_points
            for low, high in strong[name]
            for point in range(low, high + 1)
        )
    ]

    lines = [
        "-- Generated by scripts/generate_script_ranges.py; do not edit.",
        f"-- Derived from the Unicode {VERSION} Character Database: Scripts.txt,",
        "-- ScriptExtensions.txt, PropertyValueAliases.txt and",
        "-- extracted/DerivedBidiClass.txt.",
        "",
        "return {",
        f'  version = "{VERSION}",',
        "  -- Scripts written right to left.",
        "  rtl = { " + ", ".join(f"{name} = true" for name in rtl) + " },",
        "  -- Code points whose Script property is this script.",
        "  strong = {",
        *(render(name, merge(strong[name])) for name in SCRIPTS),
        "  },",
        "  -- Common or Inherited code points whose Script_Extensions include it.",
        "  ext = {",
        *(render(name, merge(extensions[name])) for name in SCRIPTS),
        "  },",
        "}",
        "",
    ]
    DESTINATION.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {DESTINATION} from the Unicode {VERSION} database")


if __name__ == "__main__":
    main()
